# Generated by Django 3.1 on 2020-08-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('genre', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=500)),
                ('year_release', models.PositiveIntegerField()),
                ('classification', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=20)),
                ('ratings', models.IntegerField()),
                ('rated', models.IntegerField()),
            ],
            options={
                'ordering': ['year_release'],
            },
        ),
    ]
