# Generated by Django 3.1 on 2020-08-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20200806_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.CharField(max_length=30),
        ),
    ]
