# Generated by Django 3.1 on 2020-08-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20200807_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rated',
            field=models.FloatField(),
        ),
    ]
