# Generated by Django 3.1 on 2020-08-09 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_remove_rates_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='rated',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='ratings',
        ),
    ]
